-- CreateEnum
CREATE TYPE "State" AS ENUM ('SEM_DESGASTE', 'DESGASTE_SEVERO', 'DESGASTE_MODERADO');

-- CreateTable
CREATE TABLE "Crosswalk" (
    "id" TEXT NOT NULL,
    "state" "State" NOT NULL DEFAULT 'SEM_DESGASTE',
    "latitude" DOUBLE PRECISION NOT NULL,
    "longitude" DOUBLE PRECISION NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Crosswalk_pkey" PRIMARY KEY ("id")
);
